server:
  PROJECT_NAME: "XXX Project"
  SERVICE_NAME: "xxx-service"
  APP_ENV: "dev"
  APP_DEBUG: true
  TIMEOUT: 15
  JWT_TOKEN_EXPIRE_TIME: 8760
  APP_VERSION: 1.0.0
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  MAX_CONN_IDLE: 5
  MAX_CONN_AGE: 5

auth:
  JWT_SECRET: "fwesg34gh34h345h54h"
  JWT_ISSUER: "xxx-service"
  JWT_AUDIENCES: "*,aud1,aud2" #comma separated, no spaces eg: "aud1,aud2,aud3"
  JWT_EXPIRATION_IN_SECONDS: 6000000000 # 10 minutes
  JWT_REFRESH_EXPIRATION_IN_SECONDS: 604800 # 7 days

swagger:
  SWAGGER_BASIC_AUTH_USERNAME:
  SWAGGER_BASIC_AUTH_PASSWORD:

cloud:
  GCP_PROJECT_IDENTIFIER:
  AWS_PROJECT_IDENTIFIER:
  GCP_SERVICE_ACCOUNT:

http:
  HOST: "127.0.0.1"
  PORT: "8080"
  TIMEOUT: 15
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  COOKIE_LIFE_TIME: 44640
  SESSION_COOKIE_NAME: "session_token"
  SSL_CERT_PATH: ""
  SSL_CERT_KEY: ""

grpc:
  PORT: "5008"
  TIMEOUT: 15
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  COOKIE_LIFE_TIME: 44640
  SESSION_COOKIE_NAME: "session_token"
  SSL_CERT_PATH: ""
  SSL_CERT_KEY: ""

logger:
  DISABLE_CALLER: false
  DISABLE_STACKTRACE: false
  ENCODING: json
  LEVEL: info

postgresql:
  HOST: "127.0.0.1"
  PORT: 5432
  USER: "postgres"
  PASS: "1q2w3e"
  DEFAULT_DB: "postgres"
  MIN_CONN: 0
  MAX_CONN: 10
  MAX_CONN_LIFETIME: 3600 #second
  MAX_CONN_IDLE_TIME: 1800 #second
  DRIVER: "pgx"

mysql:
  HOST: "127.0.0.1"
  PORT: 3306
  USER: "DB_USER"
  PASS: "PASS"
  DEFAULT_DB: "DEFAULT_DB"
  MAX_CONN: 10

mssql:
  HOST: "127.0.0.1"
  PORT: 1433
  USER: "DB_USER"
  PASS: "PASS"
  DEFAULT_DB: "DEFAULT_DB"
  MAX_CONN: 10

mongodb:
  HOST: "127.0.0.1"
  PORT:
  USER: "DB_USER"
  PASS: "PASS"
  DEFAULT_DB: "DEFAULT_DB"
  MONGO_DB_ATLAS: "mongodb+srv://{USER_NAME}:{USER_PASS}@{DB_HOST}/{DEFAULT_DB}?retryWrites=true&w=majority"

redis:
  IP: "127.0.0.1"
  PORT: 6379
  USERNAME: ""
  PASSWORD: ""
  DEFAULT_DB: 0
  MIN_IDLE_CONN: 200
  POOL_SIZE: 12000
  POOL_TIMEOUT: 240
  SERVER_CA_BASE64: ""

clickhouse:
  HOST: "127.0.0.1"
  PORT: 9000
  USER: "root"
  PASS: "password"
  DEFAULT_DB: "public"

firestore:
  PROJECT_ID: "{PROJECT_ID}"
  DEFULT_COLLECTION: "examples"
  CREDENTIALS_PATH: "config/fcm_credentials.json"

nats:
  SERVER_HOST: "127.0.0.1"
  SERVER_PORT: 4222

rabbitmq:
  URI: "amqp://admin:password@127.0.0.1:5672/"

sendgrid:
  API_KEY: ""
  FROM_NAME: "Nizam Dodanli"
  FROM_EMAIL: "nizam1@nizamdodanli.com"

google_oauth2:
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  REDIRECT_URI: ""
  SCOPES: ""

default_admin_app_user:
  USERNAME: ""
  PASSWORD: ""
  EMAIL: "ndodanli14@gmail.com"
  FIRST_NAME: "Nizam"
  LAST_NAME: "Dodanli"

