// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "ndodanli14@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app_user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Username",
                        "name": "loginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK. On success.",
                        "schema": {
                            "$ref": "#/definitions/baseres.SwaggerSuccessRes-res_LoginRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request. On any validation error.",
                        "schema": {
                            "$ref": "#/definitions/baseres.SwaggerValidationErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized.",
                        "schema": {
                            "$ref": "#/definitions/baseres.SwaggerUnauthorizedErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/baseres.SwaggerInternalErrRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "baseres.SwaggerInternalErrRes": {
            "type": "object",
            "properties": {
                "m": {
                    "type": "string",
                    "example": "Internal Server Error"
                },
                "s": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "baseres.SwaggerSuccessRes-res_LoginRes": {
            "type": "object",
            "properties": {
                "d": {
                    "$ref": "#/definitions/res.LoginRes"
                },
                "m": {
                    "type": "string",
                    "example": "XXX Created/Updated/Deleted Successfully"
                },
                "s": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "baseres.SwaggerUnauthorizedErrRes": {
            "type": "object",
            "properties": {
                "m": {
                    "type": "string",
                    "example": "Unauthorized"
                },
                "s": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "baseres.SwaggerValidationErrRes": {
            "type": "object",
            "properties": {
                "s": {
                    "type": "boolean",
                    "example": false
                },
                "v": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/baseres.ValidationError"
                    }
                }
            }
        },
        "baseres.ValidationError": {
            "type": "object",
            "properties": {
                "e": {
                    "type": "string",
                    "example": "age must be greater than 0"
                },
                "f": {
                    "type": "string",
                    "example": "age"
                }
            }
        },
        "req.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "res.LoginRes": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:5005",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Auth API",
	Description:      "This is an example server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
